### PR TITLE
test(integration): extracted common logic for setting up the proper settings content for each scenario

### PR DESCRIPTION
**Pull request by travi**
for #145

### CODE REVIEW

**Comment by travi** [comment]
hmm, build failure appears to be related to https://github.com/thlorenz/find-parent-dir/issues/8, but it is unclear to me why it shows up specifically for this PR without being an existing problem for previous builds 🤔

**Comment by travi** [comment]
it appears that we are pulling in that dependency through `prettier-standard`:

```
$ npm ls find-parent-dir
probot-settings@0.0.0-semantically-released /path/to/repository-settings/app
└─┬ prettier-standard@16.4.1
  └─┬ prettierx@0.11.3
    └── find-parent-dir@0.3.0
```

we are using the latest version of `prettier-standard`:

```
$ npm dist-tags ls prettier-standard
beta: 14.0.0-beta.5
latest: 16.4.1
```

the dependency on `prettierx` from `prettier-standard` is an exact dependency, which in turn defines an exact dependency on `find-parent-dir`, preventing updating to the fixed version of `find-parent-dir` by just updating our lockfile.

**Comment by travi** [comment]
> hmm, build failure appears to be related to [thlorenz/find-parent-dir#8](https://github.com/thlorenz/find-parent-dir/issues/8), but it is unclear to me why it shows up specifically for this PR without being an existing problem for previous builds 🤔

in the process of defining an override for the version of `find-parent-dir`, i realized that i was overlooking legit lint errors. the issue related to `find-parent-dir` is just a warning and does not fail the build. i still think we should move away from it, but that explains why it wasnt causing actual problems for us us to this point.

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
> `prettier-standard` was last published over 3 years ago, so i'd suggest we move away from it. i'd prefer to avoid making that change as part of this PR, though.

💯

**Pull request merged**
